In [1]:
import numpy as np

In [2]:
myList=[10,78,45,96]


In [5]:
myNumpyList=np.array(myList)

In [9]:
type(myNumpyList)

numpy.ndarray

In [10]:
matrixArray=[[12,45,78],[45,12,63],[36,78,12]]

In [11]:
matrixNumpyList=np.array(matrixArray)

In [12]:
matrixNumpyList

array([[12, 45, 78],
       [45, 12, 63],
       [36, 78, 12]])

### arange

**bu fonksiyon verdiğimiz sınırlar dahilinde bize int sayılar dönderir

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(45,96)

array([45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
       62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
       79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95])

In [17]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

### zeros-ones

** 0'lar oluşturmamıza yarar.Ones ise 1'ler oluşturmamıza yarar



In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones(2)

array([1., 1.])

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Linspace

** np.linspace(a,b,c)  a dan b ye kadar c tane sayı seç araları eşit olsun.

In [27]:
np.linspace(10,20,2)

array([10., 20.])

In [30]:
np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [32]:
np.linspace(0,45,5)

array([ 0.  , 11.25, 22.5 , 33.75, 45.  ])

### eye

In [33]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### random

** rastgele sayı üretilir.


In [36]:
np.random.randn(8)

array([-0.90303925,  0.07322909, -0.362625  ,  1.28233295, -1.16640784,
       -0.78220427,  0.73835497, -0.59556709])

In [38]:
np.random.randn(4,4)

array([[-1.14308515, -0.53951762,  0.68983974,  1.1349146 ],
       [-1.34877299, -0.16555412,  1.99899729, -0.28399201],
       [ 1.26152154, -0.79428456,  0.9355919 , -1.2141204 ],
       [-0.15396565, -0.01791193,  1.45201851, -0.81415734]])

In [39]:
np.random.randn(3,3)

array([[-0.57051382,  0.71329791,  0.70835564],
       [ 0.30607355, -0.95189919, -1.91082109],
       [-0.44127474,  0.49202847, -0.09374092]])

In [40]:
np.random.randn(6)

array([ 0.53855374,  0.45458039,  0.29832321, -1.75241386, -0.97086692,
       -0.6584233 ])

In [41]:
np.random.randint(1,10)

4

In [42]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.random.randint(20,50,5)

array([30, 44, 31, 43, 47])

In [48]:
np.arange(10,20,5)

array([10, 15])

In [49]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### Numpy Dizi Methodları

In [78]:
myNumpyArray=np.arange(30)

In [79]:
#Listedeki elemanları 6 satır 5 sütüna böldü

In [80]:
myNumpyArray.reshape(6,5)  

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [81]:
myNumpyArray.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [82]:
myNumpyArray2=np.arange(20)

In [83]:
myNumpyArray2.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [84]:
myNumpyArray2.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [85]:
myNumpyArray2.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [86]:
myNumpyArray3=np.arange(100)

In [87]:
myNumpyArray3.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [91]:
myNumpyArray.max()

29

In [89]:
myNumpyArray2.max()


19

In [90]:
myNumpyArray3.max()

99

In [92]:
myNumpyArray.min()

0

In [93]:
myNumpyArray2.min()

0

In [94]:
myNumpyArray3.min()


0

In [95]:
myNumpyArray2.argmax()

19

In [96]:
myNumpyArray3.argmin()

0

In [97]:
myNumpyArray3.argmax()

99

### Numpy İndeksler

In [114]:
myList2=np.arange(0,15)

In [115]:
myList2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [116]:
myList2[2]

2

In [117]:
myList2[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [118]:
myList2[2:5]

array([2, 3, 4])

In [119]:
myList2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [120]:
myList3=np.arange(12)

In [121]:
myList3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [122]:
copyList=myList3.copy()

In [123]:
copyList

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [124]:
copyList[0:4]=-200

In [125]:
copyList

array([-200, -200, -200, -200,    4,    5,    6,    7,    8,    9,   10,
         11])

In [127]:
myList3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [128]:
copyList

array([-200, -200, -200, -200,    4,    5,    6,    7,    8,    9,   10,
         11])

### Matrix İndeksleri

In [129]:
exampleList=matrixArray.copy()

In [130]:
exampleList

[[12, 45, 78], [45, 12, 63], [36, 78, 12]]

In [131]:
matrixExampleList=np.array(exampleList)

In [132]:
matrixExampleList

array([[12, 45, 78],
       [45, 12, 63],
       [36, 78, 12]])

In [133]:
matrixExampleList[2:]

array([[36, 78, 12]])

In [134]:
matrixExampleList[:]

array([[12, 45, 78],
       [45, 12, 63],
       [36, 78, 12]])

In [135]:
matrixExampleList[2][2]

12

In [136]:
matrixExampleList[2,2]

12

In [138]:
matrixExampleList[[0,2]]

array([[12, 45, 78],
       [36, 78, 12]])

### Operasyonlar

In [139]:
newArray=np.random.randint(0,100,20)

In [140]:
newArray

array([72, 52, 62, 84, 57, 92, 85, 46, 40, 66, 46, 61, 32, 44, 24, 51, 60,
        3, 93, 23])

In [141]:
newArray>24

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True, False])

In [143]:
newArray[newArray<24]

array([ 3, 23])

In [147]:
newArray2=np.random.randint(0,50,10)

In [148]:
newArray2

array([36, 24,  6, 49, 17, 28,  3, 41, 20,  0])

In [152]:
newArray2<25
    

array([False,  True,  True, False,  True, False,  True, False,  True,
        True])

In [155]:
newArray2[newArray2<25]

array([24,  6, 17,  3, 20,  0])

** numpy ile diziler birbirleriyle dört işleme tabi tutulabilirler

In [158]:
newArray3=newArray2+newArray2

In [159]:
newArray3

array([72, 48, 12, 98, 34, 56,  6, 82, 40,  0])

In [160]:
newArray4=newArray2*newArray2

In [161]:
newArray4

array([1296,  576,   36, 2401,  289,  784,    9, 1681,  400,    0])

In [162]:
newArray5=newArray2-newArray2

In [163]:
newArray5

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [165]:
## newArray6=newArray2/newArray2