In [1]:
import numpy as np
import pandas as pd

##  Series

In [2]:
myDicitionary={"İrem":21,"Zeynep":35,"Ali":24,"Zeynep":12}

In [3]:
myDicitionary

{'İrem': 21, 'Zeynep': 12, 'Ali': 24}

In [4]:
pd.Series(myDicitionary)

İrem      21
Zeynep    12
Ali       24
dtype: int64

In [5]:
myList=["Armut","Elma","Üzüm","Kiraz","Erik"]

In [6]:
pd.Series(myList)

0    Armut
1     Elma
2     Üzüm
3    Kiraz
4     Erik
dtype: object

In [7]:
mySeries=pd.Series(data=myList,index=["1.kasa","2.kasa","3. kasa","4.kasa","5. kasa"])

In [8]:
mySeries

1.kasa     Armut
2.kasa      Elma
3. kasa     Üzüm
4.kasa     Kiraz
5. kasa     Erik
dtype: object

In [9]:
yarismaSonucu1=pd.Series([10,20,30],["İrem","Mehmet","Zeynep"])


In [10]:
yarismaSonucu2=pd.Series([15,23,10],["İrem","Mehmet","Zeynep"])

In [11]:
yarismaSonucu1

İrem      10
Mehmet    20
Zeynep    30
dtype: int64

In [12]:
yarismaSonucu2

İrem      15
Mehmet    23
Zeynep    10
dtype: int64

In [13]:
sonSonuc=yarismaSonucu1+yarismaSonucu2

In [14]:
sonSonuc

İrem      25
Mehmet    43
Zeynep    40
dtype: int64

In [15]:
vizeNotları=pd.Series([45,85,55],["Ali","Ahmet","Mehmet"])

In [16]:
finalNotları=pd.Series([46,56,78],["Nergis","Salih","Ahmet"])

In [17]:
sonuc=vizeNotları+finalNotları

In [18]:
sonuc

Ahmet     163.0
Ali         NaN
Mehmet      NaN
Nergis      NaN
Salih       NaN
dtype: float64

## Data Frame

In [19]:
# Serilerin yan yana getirilmesiyle oluşan bir  excel tablosu olarak düşünülebilir.

In [20]:
data =np.random.randn(4,3)

In [21]:
data

array([[-0.43196551,  0.8815036 , -0.67735128],
       [ 0.4669139 ,  1.95997893, -1.2496912 ],
       [ 0.46053377,  0.55878846,  0.23072281],
       [-0.56544507, -0.59792984,  0.42810532]])

In [22]:
# 0. indeksi çağırdığında 0. satır gelir

In [23]:
data[0]

array([-0.43196551,  0.8815036 , -0.67735128])

In [24]:
yeniDataFrame=pd.DataFrame(data)

In [25]:
yeniDataFrame

0         1         2
0 -0.431966  0.881504 -0.677351
1  0.466914  1.959979 -1.249691
2  0.460534  0.558788  0.230723
3 -0.565445 -0.597930  0.428105

In [26]:
data2=np.random.randn(4,4)

In [27]:
data2

array([[-0.90127197,  0.23435177, -0.13717031, -1.10656918],
       [-2.20711484, -0.23721352, -1.07379838,  0.5740718 ],
       [ 0.94863029, -1.18738043, -0.18150156,  0.30864456],
       [ 0.54529487, -0.34287916,  0.49680632, -0.85285789]])

In [28]:
data2[1]

array([-2.20711484, -0.23721352, -1.07379838,  0.5740718 ])

In [29]:
yeniDataFrame2=pd.DataFrame(data2)

In [30]:
yeniDataFrame2

0         1         2         3
0 -0.901272  0.234352 -0.137170 -1.106569
1 -2.207115 -0.237214 -1.073798  0.574072
2  0.948630 -1.187380 -0.181502  0.308645
3  0.545295 -0.342879  0.496806 -0.852858

In [31]:
sınıftakiKİsiler=["Ali","Ahmet","Mehmet","Zeynep","Ayşe"]
notlar=[100,55,78,46,41]

In [32]:
sonuc=pd.DataFrame(notlar,index=sınıftakiKİsiler,columns=["Notlar"])

In [33]:
sonuc

Notlar
Ali        100
Ahmet       55
Mehmet      78
Zeynep      46
Ayşe        41

In [36]:
sinif={"isimler":["Ali","Ahmet","Mehmet"],"1.notlar":[100,55,78],"2.notlar":[45,96,78]}

In [42]:
sinifinDataFrame=pd.DataFrame(sinif,index=[1,2,3])

In [43]:
sinifinDataFrame

isimler  1.notlar  2.notlar
1     Ali       100        45
2   Ahmet        55        96
3  Mehmet        78        78

In [46]:
isciler={"yas":[32,24,58],"maaslar":[20.000,15.000,35.000]}

In [47]:
iscilerDataFrame=pd.DataFrame(isciler,index=["Ali","Ahmet","Mehmet"])

In [48]:
iscilerDataFrame

yas  maaslar
Ali      32     20.0
Ahmet    24     15.0
Mehmet   58     35.0

In [50]:
iscilerDataFrame["yas"]

Ali       32
Ahmet     24
Mehmet    58
Name: yas, dtype: int64

In [51]:
iscilerDataFrame["maaslar"]

Ali       20.0
Ahmet     15.0
Mehmet    35.0
Name: maaslar, dtype: float64

In [52]:
iscilerDataFrame[["yas","maaslar"]]

yas  maaslar
Ali      32     20.0
Ahmet    24     15.0
Mehmet   58     35.0

In [53]:
iscilerDataFrame.loc["Ali"]

yas        32.0
maaslar    20.0
Name: Ali, dtype: float64

In [54]:
iscilerDataFrame.loc["Mehmet"]

yas        58.0
maaslar    35.0
Name: Mehmet, dtype: float64

In [55]:
iscilerDataFrame.iloc[0]

yas        32.0
maaslar    20.0
Name: Ali, dtype: float64