In [1]:
import numpy as np

In [2]:
benimListem=[10,20,30,47]

In [3]:
numpyArray=np.array(benimListem)

In [4]:
type(numpyArray)

numpy.ndarray

In [5]:
matrixListem=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
matrixListem

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
numpyArrayMatrix=np.array(matrixListem)

In [8]:
numpyArrayMatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**arange() fonksiyonu içerisine yazılan sınırlar arasında int sayı döndürür.

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
np.arange(12,45)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [12]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
np.arange(89,100)

array([89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
np.arange(45,96)

array([45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
       62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
       79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95])

In [15]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [16]:
np.arange(50,100,4)

array([50, 54, 58, 62, 66, 70, 74, 78, 82, 86, 90, 94, 98])

In [17]:
zero=np.zeros(5)

In [18]:
yasListem=[12,25,48,46,12]

In [19]:
yasListem=zero

In [20]:
yasListem

array([0., 0., 0., 0., 0.])

In [21]:
one=np.ones(5)

In [22]:
yasListem=one

In [23]:
yasListem

array([1., 1., 1., 1., 1.])

**linspace() fonksiyonu seçtiğimiz aralıkta seçtiğimiz parça sayısına böler ve her parça arası eşit olur.

In [24]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [25]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [26]:
np.linspace(45,90,5)

array([45.  , 56.25, 67.5 , 78.75, 90.  ])

In [27]:
np.linspace(63,100,10)

array([ 63.        ,  67.11111111,  71.22222222,  75.33333333,
        79.44444444,  83.55555556,  87.66666667,  91.77777778,
        95.88888889, 100.        ])

In [28]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [29]:
np.random.randn(8)

array([ 1.50420777, -0.73662904, -0.57801848, -1.05258808,  0.75231495,
        0.10519285, -1.78047658,  0.94457149])

In [30]:
np.random.randn(5)

array([-2.19166947, -0.56904728, -0.28831785,  0.82457464, -0.65571431])

In [31]:
np.random.randn(2)

array([-0.96502039, -0.18043707])

In [32]:
np.random.randn(5)

array([-0.70240127, -0.62532435,  1.83471416, -0.92504308, -0.180218  ])

In [33]:
np.random.randn(20)

array([ 0.74932735, -0.20564512, -0.79033478,  0.63224416, -1.29542093,
        0.8926649 , -0.09105368,  1.41062658,  0.12318133,  0.764863  ,
        2.7919458 ,  0.78030898, -0.17178159, -1.26197361,  2.74798585,
       -0.53899471, -0.27607857,  0.77739179, -0.81632258, -0.70673146])

In [34]:
np.random.randn(4,4)

array([[ 0.88391942, -0.8349791 , -0.0357261 , -2.03831943],
       [-0.52676569,  0.53622375, -0.61437375,  0.88692641],
       [-1.05535697, -0.91955454, -0.76843677,  1.78179954],
       [-0.09136913,  0.78797222, -1.09913087, -0.12954091]])

In [35]:
np.random.randn(3,3)

array([[-1.5443813 ,  0.14844923, -1.00342166],
       [-1.41823121, -1.77719837,  0.44380526],
       [ 1.25413611, -1.27544185,  0.17777712]])

In [36]:
np.random.randn(2,2)

array([[-0.69423245,  1.51628331],
       [ 0.29506028, -0.65462041]])

In [37]:
np.random.randint(1,10)

3

In [38]:
np.random.randint(1,100,2)

array([53,  4])

In [39]:
np.random.randint(3)

2

In [40]:
np.random.randint(3,45,3)

array([35, 26,  6])

In [41]:
benimNumpyDizim=np.arange(30)

In [42]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [43]:
matrixNumpyDizim=benimNumpyDizim.reshape(6,5)

In [44]:
matrixNumpyDizim

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [45]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [46]:
benimNumpyDizim.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [47]:
benimNumpyDizim.max()

29

In [48]:
benimNumpyDizim.min()

0

In [49]:
benimNumpyDizim.argmax()

29

In [50]:
benimNumpyDizim.argmin()

0

In [51]:
matrixNumpyDizim.shape

(6, 5)

In [52]:
matrixNumpyDizim[3]

array([15, 16, 17, 18, 19])

In [53]:
matrixNumpyDizim[2:4]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [54]:
yeniMatrix=matrixNumpyDizim.copy()

In [55]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [56]:
yeniMatrix[3][4]=25

In [57]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 25],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [58]:
yeniMatrix[:]=700

In [59]:
yeniMatrix

array([[700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700]])

In [60]:
yeniMatrix

array([[700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700],
       [700, 700, 700, 700, 700]])

In [61]:
matrixNumpyDizim

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [62]:
matrixNumpyDizim[1,2]

7

In [63]:
matrixNumpyDizim[1:,2]

array([ 7, 12, 17, 22, 27])

In [64]:
matrixNumpyDizim[[2,3]]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [65]:
matrixNumpyDizim[2:4]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [66]:
yeniDizi=np.random.randint(1,100,20)

In [67]:
yeniDizi

array([56, 95, 97, 48, 17, 43, 32,  7, 44, 21, 92,  3,  9, 28, 10, 78, 87,
       39, 36,  8])

In [68]:
yeniDizi>20

array([ True,  True,  True,  True, False,  True,  True, False,  True,
        True,  True, False, False,  True, False,  True,  True,  True,
        True, False])

In [69]:
sayı=yeniDizi[yeniDizi>20]

In [70]:
len(sayı)

14

In [71]:
sayı

array([56, 95, 97, 48, 43, 32, 44, 21, 92, 28, 78, 87, 39, 36])

In [72]:
yeniDizi2=np.random.randint(1,50,20)

In [73]:
toplamSonuc=yeniDizi+yeniDizi2

In [74]:
yeniDizi2

array([ 1, 22, 23, 30, 34, 23, 28, 26, 47, 17, 23, 28, 32, 25, 43,  8, 12,
        7, 20, 49])

In [75]:
toplamSonuc

array([ 57, 117, 120,  78,  51,  66,  60,  33,  91,  38, 115,  31,  41,
        53,  53,  86,  99,  46,  56,  57])

In [76]:
sonucCarpma=yeniDizi*yeniDizi2

In [77]:
sonucCarpma

array([  56, 2090, 2231, 1440,  578,  989,  896,  182, 2068,  357, 2116,
         84,  288,  700,  430,  624, 1044,  273,  720,  392])

In [78]:
sonucCikarma=yeniDizi-yeniDizi2

In [79]:
sonucCikarma

array([ 55,  73,  74,  18, -17,  20,   4, -19,  -3,   4,  69, -25, -23,
         3, -33,  70,  75,  32,  16, -41])

In [80]:
sonucBolme=yeniDizi/yeniDizi2

In [81]:
sonucBolme

array([56.        ,  4.31818182,  4.2173913 ,  1.6       ,  0.5       ,
        1.86956522,  1.14285714,  0.26923077,  0.93617021,  1.23529412,
        4.        ,  0.10714286,  0.28125   ,  1.12      ,  0.23255814,
        9.75      ,  7.25      ,  5.57142857,  1.8       ,  0.16326531])

In [82]:
liste1=[1,2]
liste2=[3,4]

In [83]:
toplam=liste1+liste2

In [84]:
toplam

[1, 2, 3, 4]

In [85]:
np.sqrt(4)

2.0

## Pandas Tekrarı

In [86]:
sozluk={"İsim":["Ali","mehmet","Canan","Zeynep"],"Yaş":[25,28,36.45]}

In [87]:
sozluk


{'İsim': ['Ali', 'mehmet', 'Canan', 'Zeynep'], 'Yaş': [25, 28, 36.45]}

In [88]:
import pandas as pd

In [89]:
pd.Series(sozluk)

İsim    [Ali, mehmet, Canan, Zeynep]
Yaş                  [25, 28, 36.45]
dtype: object

In [90]:
adlar=["Ali","Ahmet","Mehmet","Zeynep"]
yaslar=[21,34,25,27]

In [91]:
pd.Series(yaslar,adlar)

Ali       21
Ahmet     34
Mehmet    25
Zeynep    27
dtype: int64

In [92]:
puanlar1=pd.Series([10,20,30],["Ali","Ayşe","Fatma"])

In [93]:
puanlar2=pd.Series([20,45,50],["Ali","Ayşe","Fatma"])

In [94]:
sonuc=puanlar1+puanlar2

In [95]:
sonuc

Ali      30
Ayşe     65
Fatma    80
dtype: int64

In [96]:
kalori1=pd.Series([100,200,50],["yumurta","peynir","domates"])
kalori2=pd.Series([100,400,50],["yumurta","peynir","domates"])

In [97]:
gunSonu=kalori1+kalori2

In [98]:
gunSonu

yumurta    200
peynir     600
domates    100
dtype: int64

In [99]:
kumeDataFrame=np.random.randn(4,4)

In [100]:
kumeDataFrame

array([[ 0.32069959,  1.24989015, -0.80641142,  1.41717282],
       [ 0.6312091 , -0.96965876,  0.4424149 , -1.14247061],
       [-0.54888656, -0.62259607, -1.2444694 , -0.83349272],
       [-1.03567387,  1.94973493, -0.03310222, -0.88493781]])

In [101]:
yeniDataFrame=pd.DataFrame(kumeDataFrame,index=["1.satır","2.satır","3.satır","4.satır"],columns=["1.kolon","2.kolon","3.kolon","4.kolon"])

In [102]:
yeniDataFrame

1.kolon   2.kolon   3.kolon   4.kolon
1.satır  0.320700  1.249890 -0.806411  1.417173
2.satır  0.631209 -0.969659  0.442415 -1.142471
3.satır -0.548887 -0.622596 -1.244469 -0.833493
4.satır -1.035674  1.949735 -0.033102 -0.884938

In [103]:
yeniDataFrame["1.kolon"]

1.satır    0.320700
2.satır    0.631209
3.satır   -0.548887
4.satır   -1.035674
Name: 1.kolon, dtype: float64

In [104]:
yeniDataFrame["2.kolon"]

1.satır    1.249890
2.satır   -0.969659
3.satır   -0.622596
4.satır    1.949735
Name: 2.kolon, dtype: float64

In [105]:
yeniDataFrame["3.kolon"]

1.satır   -0.806411
2.satır    0.442415
3.satır   -1.244469
4.satır   -0.033102
Name: 3.kolon, dtype: float64

In [106]:
yeniDataFrame["4.kolon"]

1.satır    1.417173
2.satır   -1.142471
3.satır   -0.833493
4.satır   -0.884938
Name: 4.kolon, dtype: float64

In [107]:
yeniDataFrame.loc["1.satır"]

1.kolon    0.320700
2.kolon    1.249890
3.kolon   -0.806411
4.kolon    1.417173
Name: 1.satır, dtype: float64

In [108]:
yeniDataFrame.loc["2.satır"]

1.kolon    0.631209
2.kolon   -0.969659
3.kolon    0.442415
4.kolon   -1.142471
Name: 2.satır, dtype: float64

#

In [111]:
yeniDataFrame.drop("4.kolon",axis=1)

1.kolon   2.kolon   3.kolon
1.satır  0.320700  1.249890 -0.806411
2.satır  0.631209 -0.969659  0.442415
3.satır -0.548887 -0.622596 -1.244469
4.satır -1.035674  1.949735 -0.033102

In [112]:
yeniDataFrame

1.kolon   2.kolon   3.kolon   4.kolon
1.satır  0.320700  1.249890 -0.806411  1.417173
2.satır  0.631209 -0.969659  0.442415 -1.142471
3.satır -0.548887 -0.622596 -1.244469 -0.833493
4.satır -1.035674  1.949735 -0.033102 -0.884938

In [113]:
yeniDataFrame.drop("3.kolon",axis=1)

1.kolon   2.kolon   4.kolon
1.satır  0.320700  1.249890  1.417173
2.satır  0.631209 -0.969659 -1.142471
3.satır -0.548887 -0.622596 -0.833493
4.satır -1.035674  1.949735 -0.884938

In [114]:
yeniDataFrame

1.kolon   2.kolon   3.kolon   4.kolon
1.satır  0.320700  1.249890 -0.806411  1.417173
2.satır  0.631209 -0.969659  0.442415 -1.142471
3.satır -0.548887 -0.622596 -1.244469 -0.833493
4.satır -1.035674  1.949735 -0.033102 -0.884938

In [116]:
yeniDataFrame.drop("3.satır",axis=0)

1.kolon   2.kolon   3.kolon   4.kolon
1.satır  0.320700  1.249890 -0.806411  1.417173
2.satır  0.631209 -0.969659  0.442415 -1.142471
4.satır -1.035674  1.949735 -0.033102 -0.884938

In [117]:
yeniDataFrame

1.kolon   2.kolon   3.kolon   4.kolon
1.satır  0.320700  1.249890 -0.806411  1.417173
2.satır  0.631209 -0.969659  0.442415 -1.142471
3.satır -0.548887 -0.622596 -1.244469 -0.833493
4.satır -1.035674  1.949735 -0.033102 -0.884938

In [118]:
yepYeniDataFrame=yeniDataFrame.copy()

In [119]:
yepYeniDataFrame.drop("4.kolon",axis=1,inplace=True)

In [120]:
yepYeniDataFrame

1.kolon   2.kolon   3.kolon
1.satır  0.320700  1.249890 -0.806411
2.satır  0.631209 -0.969659  0.442415
3.satır -0.548887 -0.622596 -1.244469
4.satır -1.035674  1.949735 -0.033102

In [121]:
yepYeniDataFrame.drop("4.satır",axis=0,inplace=True)

In [122]:
yepYeniDataFrame


1.kolon   2.kolon   3.kolon
1.satır  0.320700  1.249890 -0.806411
2.satır  0.631209 -0.969659  0.442415
3.satır -0.548887 -0.622596 -1.244469

In [123]:
yepYeniDataFrame.loc["1.satır"]["1.kolon"]

0.32069959365792394

In [124]:
yepYeniDataFrame.loc["1.satır","1.kolon"]

0.32069959365792394

In [127]:
deger=yepYeniDataFrame[:]>0

In [128]:
yepYeniDataFrame[deger]

1.kolon  2.kolon   3.kolon
1.satır  0.320700  1.24989       NaN
2.satır  0.631209      NaN  0.442415
3.satır       NaN      NaN       NaN

In [129]:
yepYeniDataFrame[yepYeniDataFrame[:]>0]

1.kolon  2.kolon   3.kolon
1.satır  0.320700  1.24989       NaN
2.satır  0.631209      NaN  0.442415
3.satır       NaN      NaN       NaN

**yepYeniDataFrame.reset_index()

In [146]:
yepYeniDataFrame

level_0    index   1.kolon   2.kolon   3.kolon
0        0  1.satır  0.320700  1.249890 -0.806411
1        1  2.satır  0.631209 -0.969659  0.442415
2        2  3.satır -0.548887 -0.622596 -1.244469